### PR TITLE
I broke something

### PR DESCRIPTION
**Pull request by regexbuster**
almost there. don't merge yet

### CODE REVIEW

**Comment by regexbuster** [comment]
okay I actually think I fixed it this time. some things might have been changed back from where it was in main. however, this technically fixes the explore page. feel free to merge when ready

**Comment by AjaiKN** [comment]
Try moving your mouse slowly from the outer edge into one of them. For me, it flickers a lot.

Maybe we should just not do the shrinking?

**Comment by AjaiKN** [comment]
Actually, it might be a device-specific thing. I'll send you a screen recording.

**Comment by AjaiKN** [comment]
Also, there's a 4 (or 14?) at the top.

image

**Comment by AjaiKN** [comment]
Wait, that last problem might not have been something you changed. I think that may have just been something that was updated on main since your branch diverged.

**Comment by AjaiKN** [comment]
I'm going to merge this and then comment out the hover styles.

**Pull request merged**
